server:
  port: 8385

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: false
    config:
      enabled: false
  main:
    banner-mode: off
  zipkin:
    enabled: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    non-secure-port: 8761
    initial-status: STARTING
    preferIpAddress: true

logging:
  level:
    root: INFO
    com.backbase: DEBUG
    org.springframework: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    httpclient.wire: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

backbase:
  security:
    public:
      paths: /**
    mtls:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

drive-wealth:
  dwClientAppKey: ef948945-1b2f-45b1-a425-6ab2ed7a1a6d
  clientID: 0oa69qz360MigPNAc1d7
  clientSecret: KJOtHe9uSVtwrQ_XCIXayQCIKcAFlgiB7an-id5-
